<!-- Write a function retry(fn, retries) that tries to call fn and if it fails (throws error), retries up to retries times using a callback. -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title>Retry Function Using Callbacks</title>
    <meta name="description" content="Contains the Retry Function Using Callbacks">
</head>

<body>
    <script>
        function retry(fn, retries) {
            try {
                fn();
            }
            catch (err) {
                if (retries > 0) {
                    console.log(`Retrying... Attempt Left : ${retries}`);
                    retry(fn, retries - 1);
                }
                else {
                    console.log("All the Retries Failed !");
                }
            }
        }
        let count = 0;
        function unstableTask() {
            count++;
            if (count < 5) throw new Error("Failed");
            console.log(`Success On Attempt : ${count}`);
        }

        retry(unstableTask, 3);
    </script>
</body>

</html>